import { Inter } from "next/font/google";
import "@/src/styles/globals.css";
import NavBar from "../components/NavBar";
import { Toaster } from "@/src/components/ui/toaster";
import { EdgeStoreProvider } from "@/src/lib/edgestore";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen">
          <NavBar />
          <main className="flex flex-1 justify-center overflow-hidden">
            <EdgeStoreProvider>{children}</EdgeStoreProvider>
          </main>
          <Toaster />
        </div>
      </body>
    </html>
  );
}
